#!/bin/sh
#
# bootstrap
#
set -e

#
# Check for Bundler
#
if test ! $(which bundle)
then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
else
  echo "  + Bundler found."
fi

# createdb --owner=nilcolor -E UTF8 -l en_US.UTF-8 -T template0 steam_dev
# CREATE EXTENSION hstore;
psql -d steam_dev -c "CREATE EXTENSION hstore"
#
# Install gems
#
echo "  + Bootstrapping your Rubies."
bundle install --binstubs .bundle/bin --path vendor/gems --quiet
